In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv(r'C:\Users\adity\Downloads\Dyashin Technosoft DS Internship\Datasets\movie_metadata.csv')
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [4]:
df.shape

(4917, 28)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4917 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      4898 non-null   object
 1   director_name              4815 non-null   object
 2   num_critic_for_reviews     4868 non-null   float64
 3   duration                   4902 non-null   float64
 4   director_facebook_likes    4815 non-null   float64
 5   actor_3_facebook_likes     4894 non-null   float64
 6   actor_2_name               4904 non-null   object
 7   actor_1_facebook_likes     4910 non-null   float64
 8   gross                      4054 non-null   float64
 9   genres                     4917 non-null   object
 10  actor_1_name               4910 non-null   object
 11  movie_title                4917 non-null   object
 12  num_voted_users            4917 non-null   int64
 13  cast_total_facebook_likes  4917 non-null   int64
 14  actor_3_name               4894 non-null   object
 15  facenumber_in_poster       4904 non-null   float64
 16  plot_keywords              4765 non-null   object
 17  movie_imdb_link            4917 non-null   object
 18  num_user_for_reviews       4896 non-null   float64
 19  language                   4903 non-null   object
 20  country                    4912 non-null   object
 21  content_rating             4617 non-null   object
 22  budget                     4433 non-null   float64
 23  title_year                 4811 non-null   float64
 24  actor_2_facebook_likes     4904 non-null   float64
 25  imdb_score                 4917 non-null   float64
 26  aspect_ratio               4591 non-null   float64
 27  movie_facebook_likes       4917 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [6]:
df.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4868.000000,4902.000000,4815.000000,4894.000000,4910.000000,4.054000e+03,4.917000e+03,4917.000000,4904.000000,4896.000000,4.433000e+03,4811.000000,4904.000000,4917.000000,4591.000000,4917.000000
mean,137.983566,107.089963,690.871028,631.203515,6493.369450,4.764451e+07,8.263723e+04,9578.276998,1.377039,267.651348,3.654150e+07,2002.443567,1621.649470,6.437584,2.222267,7346.799675
std,120.227603,25.283503,2832.677373,1625.716627,15105.651622,6.737255e+07,1.383091e+05,18162.789993,2.023715,372.898753,1.002322e+08,12.455838,4010.936348,1.127740,1.402798,19204.348861
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,49.000000,93.000000,7.000000,132.000000,607.000000,5.019656e+06,8.367000e+03,1395.000000,0.000000,64.000000,6.000000e+06,1999.000000,277.000000,5.800000,1.850000,0.000000
50%,108.000000,103.000000,48.000000,366.000000,982.000000,2.504396e+07,3.315800e+04,3049.000000,1.000000,153.500000,1.980000e+07,2005.000000,593.000000,6.600000,2.350000,158.000000
75%,191.000000,118.000000,189.500000,633.000000,11000.000000,6.110841e+07,9.376700e+04,13616.000000,2.000000,320.250000,4.300000e+07,2011.000000,912.000000,7.200000,2.350000,2000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,4.200000e+09,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [3]:
# Remove duplicates
df = df.drop_duplicates(subset=["movie_title"])

In [7]:
df["movie_title"] = df["movie_title"].str.strip()

C:\Users\adity\AppData\Local\Temp\ipykernel_62508\1222972427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["movie_title"] = df["movie_title"].str.strip()

In [8]:
df = df.dropna(subset=["gross","budget","imdb_score"])

In [11]:
df.isna().sum().sum()

206

In [13]:
df = df.dropna(subset=["gross", "budget"])

In [14]:
df = df.dropna(subset=["imdb_score"])

In [15]:
df["director_name"] = df["director_name"].fillna("Unknown")
df["actor_1_name"] = df["actor_1_name"].fillna("Unknown")
df["actor_2_name"] = df["actor_2_name"].fillna("Unknown")
df["actor_3_name"] = df["actor_3_name"].fillna("Unknown")

In [16]:
df["genres"] = df["genres"].fillna("Unknown")

In [19]:
df.isnull().sum().sum()

188

In [21]:
df

,movie_title,director_name,genres,gross,budget,imdb_score,num_critic_for_reviews,num_voted_users,actor_1_name,actor_2_name,actor_3_name,profit
0,Avatar,James Cameron,Action|Adventure|Fantasy|Sci-Fi,760505847.0,237000000.0,7.9,723.0,886204,CCH Pounder,Joel David Moore,Wes Studi,523505847.0
1,Pirates of the Caribbean: At World's End,Gore Verbinski,Action|Adventure|Fantasy,309404152.0,300000000.0,7.1,302.0,471220,Johnny Depp,Orlando Bloom,Jack Davenport,9404152.0
2,Spectre,Sam Mendes,Action|Adventure|Thriller,200074175.0,245000000.0,6.8,602.0,275868,Christoph Waltz,Rory Kinnear,Stephanie Sigman,-44925825.0
3,The Dark Knight Rises,Christopher Nolan,Action|Thriller,448130642.0,250000000.0,8.5,813.0,1144337,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,198130642.0
5,John Carter,Andrew Stanton,Action|Adventure|Sci-Fi,73058679.0,263700000.0,6.6,462.0,212204,Daryl Sabara,Samantha Morton,Polly Walker,-190641321.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Primer,Shane Carruth,Drama|Sci-Fi|Thriller,424760.0,7000.0,7.0,143.0,72639,Shane Carruth,David Sullivan,Casey Gooden,417760.0
5034,Cavite,Neill Dela Llana,Thriller,70071.0,7000.0,6.3,35.0,589,Ian Gamazon,Edgar Tancangco,Quynn Ton,63071.0
5035,El Mariachi,Robert Rodriguez,Action|Crime|Drama|Romance|Thriller,2040920.0,7000.0,6.9,56.0,52055,Carlos Gallardo,Peter Marquardt,Consuelo Gómez,2033920.0
5037,Newlyweds,Edward Burns,Comedy|Drama,4584.0,9000.0,6.4,14.0,1338,Kerry Bishé,Caitlin FitzGerald,Daniella Pineda,-4416.0
5042,My Date with Drew,Jon Gunn,Documentary,85222.0,1100.0,6.6,43.0,4285,John August,Brian Herzlinger,Jon Gunn,84122.0

In [22]:
# Create profit column
df["profit"] = df["gross"] - df["budget"]

# 1. Find the movies with the highest profit

In [23]:
top_profit = df.sort_values("profit", ascending=False)[
    ["movie_title","profit"]
].head(10)

print(top_profit)

                                    movie_title       profit
0                                        Avatar  523505847.0
29                               Jurassic World  502177271.0
26                                      Titanic  458672302.0
3024         Star Wars: Episode IV - A New Hope  449935665.0
3080                 E.T. the Extra-Terrestrial  424449459.0
17                                 The Avengers  403279547.0
509                               The Lion King  377783777.0
240   Star Wars: Episode I - The Phantom Menace  359544677.0
66                              The Dark Knight  348316061.0
439                            The Hunger Games  329999255.0

# 2. Top 100 Movies by IMDb Rank

In [ ]:
top100 = df.sort_values("imdb_score", ascending=False)[["movie_title","imdb_score"]].head(100)
print(top100)

                              movie_title  imdb_score
1937             The Shawshank Redemption         9.3
3466                        The Godfather         9.2
2837               The Godfather: Part II         9.0
66                        The Dark Knight         9.0
3355                         Pulp Fiction         8.9
...                                   ...         ...
4000             The Secret in Their Eyes         8.2
3550                            Incendies         8.2
338                          Finding Nemo         8.2
4458  Lock, Stock and Two Smoking Barrels         8.2
960                        V for Vendetta         8.2

[100 rows x 2 columns]

# 3. Best Director

In [26]:
best_director = df.groupby("director_name")["imdb_score"].mean().sort_values(ascending=False)
print(best_director.head(10))

director_name
Charles Chaplin      8.600000
Tony Kaye            8.600000
Majid Majidi         8.500000
Damien Chazelle      8.500000
Alfred Hitchcock     8.500000
Ron Fricke           8.500000
Sergio Leone         8.433333
Christopher Nolan    8.425000
Asghar Farhadi       8.400000
S.S. Rajamouli       8.400000
Name: imdb_score, dtype: float64

# 4. Most Popular Genres

In [27]:
popular_genres = df["genres"].str.split("|").explode().value_counts()
print(popular_genres)

genres
Drama          1913
Comedy         1491
Thriller       1087
Action          935
Romance         868
Adventure       766
Crime           703
Fantasy         496
Sci-Fi          483
Family          442
Horror          378
Mystery         377
Biography       242
Animation       197
War             159
Music           159
History         153
Sport           147
Musical         102
Documentary      67
Western          60
Short             2
Film-Noir         1
Name: count, dtype: int64

# 5. Critic Favourite Actor

In [ ]:
critic_actor = df.melt(id_vars=["num_critic_for_reviews"],value_vars=["actor_1_name","actor_2_name","actor_3_name"],
value_name="actor")
critic_fav = critic_actor.groupby("actor")["num_critic_for_reviews"].mean().sort_values(ascending=False)
print(critic_fav.head(10))

actor
Amy Warren          738.0
Basher Savage       738.0
Phaldut Sharma      738.0
Russ Tamblyn        676.0
Anthony Reynolds    673.0
Alan D. Purwin      673.0
Dwight Henry        663.0
Gina Montana        663.0
Stephanie Sigman    602.0
Craig Stark         596.0
Name: num_critic_for_reviews, dtype: float64